<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Flight (1)</name>
   <tag></tag>
   <elementGuidId>f7e6cd91-d626-4554-b245-9b091bedb14f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@value='147']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=tab[name=&quot;Flight&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>da5e609d-0f3e-40c8-8d60-bf75d97da58f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>02905dca-f485-40b6-8d8f-a89bd608713b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>cf94e0a2-5847-46d6-97cc-09d26330e719</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>1154d862-a682-4a7b-8b5e-5d1c32fa4b6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2faf9305-034a-4a88-a095-0710ca1c7c3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>147</value>
      <webElementGuid>7be1d0b8-1664-4ae1-afcf-65cf8a4c2017</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-17k67my ehv0kkf3</value>
      <webElementGuid>d6876d29-c25f-4e74-85f7-2c5ebc93b7dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-slug</name>
      <type>Main</type>
      <value>https://www.tokopedia.com/flight/?t_id=1740238483851&amp;t_st=1&amp;t_pp=&amp;t_efo=&amp;t_ef=&amp;t_sm=dg_homepage_page_dg_home_desktop_other_module&amp;t_spt=</value>
      <webElementGuid>fe826c94-d649-46bc-b55f-f305851a3204</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tracker</name>
      <type>Main</type>
      <value>Flight</value>
      <webElementGuid>85d8a962-e4f2-433b-8264-10a24b641c1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Flight</value>
      <webElementGuid>6cb3821c-acb8-4d43-9a38-128dcb42f020</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;zeus-root&quot;)/div[@class=&quot;css-8atqhb&quot;]/main[@class=&quot;css-15x0u31&quot;]/section[@class=&quot;css-stopwq bordered&quot;]/div[@class=&quot;css-3kh9t4&quot;]/div[@class=&quot;css-1ukamyt m24&quot;]/div[@class=&quot;css-1cysb4j even left&quot;]/section[@class=&quot;css-7lrhbb-unf-card eeeacht0&quot;]/section[@class=&quot;css-1gw7mzg&quot;]/div[@class=&quot;css-iijm2c&quot;]/div[@class=&quot;css-g90k5e&quot;]/div[@class=&quot;css-1ekgys2&quot;]/div[@class=&quot;css-1bl48du-unf-tab-wrapper ehv0kkf0&quot;]/div[@class=&quot;css-dhcw9e-unf-tab-holder ehv0kkf2&quot;]/button[@class=&quot;css-17k67my ehv0kkf3&quot;]</value>
      <webElementGuid>f558fd25-7483-43ec-9c87-7707f295a57f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@value='147']</value>
      <webElementGuid>806a4969-2c29-46ff-adc2-30a0a887c5a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='zeus-root']/div/main/section/div/div/div[2]/section/section/div/div/div/div/div/button[3]</value>
      <webElementGuid>d25ad71b-2cf6-450f-b08a-327f1b874f16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lihat Semua'])[1]/following::button[3]</value>
      <webElementGuid>46e64f19-ef34-415f-92b7-77becb6907a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Top Up &amp; Tagihan'])[1]/following::button[3]</value>
      <webElementGuid>496d78f8-c1bf-4bd6-b1b5-40f2fd77020a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nomor Telepon'])[1]/preceding::button[3]</value>
      <webElementGuid>4118c16b-4e90-44ee-92d7-a7091d98e78f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nominal'])[1]/preceding::button[3]</value>
      <webElementGuid>ecdee652-3b87-49a4-bf05-9a912ef9d62b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div/div/div/div/div/button[3]</value>
      <webElementGuid>f1806455-d505-44f2-9b14-2bb99f59663a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Flight' or . = 'Flight')]</value>
      <webElementGuid>b9e422eb-d4d3-480f-a779-488dce18c97e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
