<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>buttonFlight</name>
   <tag></tag>
   <elementGuidId>cd3bb845-dc4e-4676-b2c7-79b9b3b5a2d3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@value='147']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=tab[name=&quot;Flight&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>902832de-7353-4fcb-bde1-c94bf7f9aba2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>96ca05b1-ad76-445b-b937-fde9ea38f46b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>55069e40-40bc-4c8d-bf3c-f810c4f3f2c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>362d5633-e2a8-4b31-b9f5-32319af9c504</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>163d95f6-d132-4aeb-a48e-96f398bcc682</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>147</value>
      <webElementGuid>b359e368-5cea-43a5-93e9-53cd58ec0b0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-17k67my ehv0kkf3</value>
      <webElementGuid>87257aa1-b216-4381-874e-fe3473130811</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-slug</name>
      <type>Main</type>
      <value>https://www.tokopedia.com/flight/?t_id=1740238143495&amp;t_st=1&amp;t_pp=&amp;t_efo=&amp;t_ef=&amp;t_sm=dg_homepage_page_dg_home_desktop_other_module&amp;t_spt=</value>
      <webElementGuid>8a635951-f448-40cf-8627-0d7c6aaef210</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tracker</name>
      <type>Main</type>
      <value>Flight</value>
      <webElementGuid>96281cce-27f9-4392-9a8a-c61fa1c72804</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Flight</value>
      <webElementGuid>d0ccd253-1969-4857-b43d-916041f537a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;zeus-root&quot;)/div[@class=&quot;css-8atqhb&quot;]/main[@class=&quot;css-15x0u31&quot;]/section[@class=&quot;css-stopwq bordered&quot;]/div[@class=&quot;css-3kh9t4&quot;]/div[@class=&quot;css-1ukamyt m24&quot;]/div[@class=&quot;css-1cysb4j even left&quot;]/section[@class=&quot;css-7lrhbb-unf-card eeeacht0&quot;]/section[@class=&quot;css-1gw7mzg&quot;]/div[@class=&quot;css-iijm2c&quot;]/div[@class=&quot;css-g90k5e&quot;]/div[@class=&quot;css-1ekgys2&quot;]/div[@class=&quot;css-1bl48du-unf-tab-wrapper ehv0kkf0&quot;]/div[@class=&quot;css-dhcw9e-unf-tab-holder ehv0kkf2&quot;]/button[@class=&quot;css-17k67my ehv0kkf3&quot;]</value>
      <webElementGuid>ce42a6d6-77b0-4a55-88b9-128c1fbfe4c2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@value='147']</value>
      <webElementGuid>590cdfe0-1d8f-4410-86b2-fbdac014af31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='zeus-root']/div/main/section/div/div/div[2]/section/section/div/div/div/div/div/button[3]</value>
      <webElementGuid>4acb1e5d-e124-49a8-bb44-bb7e59cdd49b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lihat Semua'])[1]/following::button[3]</value>
      <webElementGuid>129c23d5-ef60-40c4-9964-17f07603b1ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Top Up &amp; Tagihan'])[1]/following::button[3]</value>
      <webElementGuid>2434ca8b-8e57-4487-91a6-d8e44b624289</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nomor Telepon'])[1]/preceding::button[3]</value>
      <webElementGuid>e73d257c-fbb8-4c5f-9cfe-6ecf71641887</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nominal'])[1]/preceding::button[3]</value>
      <webElementGuid>2da2a4c8-1ff1-4cbb-9900-f9d3ef59af61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div/div/div/div/div/button[3]</value>
      <webElementGuid>f832d9e7-555a-409a-8964-2b228341690f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Flight' or . = 'Flight')]</value>
      <webElementGuid>2b7d1f60-2d2f-4d3a-90f9-1251d61ebc91</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
