<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>buttonDetail</name>
   <tag></tag>
   <elementGuidId>b8971141-843b-4145-9c69-288b4089ecef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='pdp_comp-product_detail']/div[2]/div/div/button/p</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.css-78ch3k-unf-tab-holder.ehv0kkf2 > button.tab-item.css-3lvael.ehv0kkf3 > p.css-l5do8o-unf-heading.e1qvo2ff8</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=&quot;tabPDPDetail&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>0b3f901b-3050-4b17-89f4-c269fc214bb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-unify</name>
      <type>Main</type>
      <value>Typography</value>
      <webElementGuid>23fbb96d-e762-403e-85db-a81ab9b19c43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-l5do8o-unf-heading e1qvo2ff8</value>
      <webElementGuid>1a3fadac-cd2e-491d-b0ca-6acd20d47bb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Detail</value>
      <webElementGuid>2135668d-23f3-4d00-b744-1498e574af33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pdp_comp-product_detail&quot;)/div[2]/div[@class=&quot;css-1bl48du-unf-tab-wrapper ehv0kkf0&quot;]/div[@class=&quot;css-78ch3k-unf-tab-holder ehv0kkf2&quot;]/button[@class=&quot;tab-item css-3lvael ehv0kkf3&quot;]/p[@class=&quot;css-l5do8o-unf-heading e1qvo2ff8&quot;]</value>
      <webElementGuid>3b7d45be-6e64-41ba-96ad-eb7fe88cc74b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pdp_comp-product_detail']/div[2]/div/div/button/p</value>
      <webElementGuid>e0421e38-6893-410a-b0fd-e8b87489ef43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ungu'])[1]/following::p[1]</value>
      <webElementGuid>b758b5d5-7295-49cc-8034-4685f7cd1743</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kondisi:'])[1]/preceding::p[2]</value>
      <webElementGuid>8caa0839-119d-4a3e-ac4b-31ffdf6d03cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Baru'])[1]/preceding::p[2]</value>
      <webElementGuid>0fc9d92d-825e-44d5-8b41-2b31b9bcc70a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Detail']/parent::*</value>
      <webElementGuid>57423ec6-bad9-4079-a382-f760a36ec8d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/button/p</value>
      <webElementGuid>d64e7999-44e3-46a9-8c7a-af3cd74cb6d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Detail' or . = 'Detail')]</value>
      <webElementGuid>684a5ae5-0908-4e39-918b-ba948cd077c7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
