<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>buttonGoToShopPage</name>
   <tag></tag>
   <elementGuidId>7ffb7ace-2fd2-40ab-89f1-1a8400fdaf3e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='pdp_comp-shop_credibility']/div[2]/div/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.css-1nf4dbc</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Logo 4gungsh0p&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>11aafe4e-cbaa-4eac-b793-7ec1d6e1c799</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>imgPDPFooterShopBadge</value>
      <webElementGuid>6b3e7c1b-5a46-4f48-9ac0-606a8f22993b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-1nf4dbc</value>
      <webElementGuid>9747064b-96dc-4cc8-9041-81ffb67b75bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://images.tokopedia.net/img/seller_no_logo_1.png</value>
      <webElementGuid>7ef27974-388b-4b45-8f15-415faf5faf52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Logo 4gungsh0p</value>
      <webElementGuid>bc4665d8-f2d3-489e-ab13-53d88ff6d249</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pdp_comp-shop_credibility&quot;)/div[@class=&quot;css-1mxqisk&quot;]/div[@class=&quot;css-3v9jg2&quot;]/a[1]/img[@class=&quot;css-1nf4dbc&quot;]</value>
      <webElementGuid>45ea1592-0637-4487-b22d-b99c173d3df4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pdp_comp-shop_credibility']/div[2]/div/a/img</value>
      <webElementGuid>cab47ada-f107-4a9e-bfc0-0767886a38eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Logo 4gungsh0p']</value>
      <webElementGuid>0cc909f3-dbeb-4fdc-a1b0-851ad9ac0cd6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/a/img</value>
      <webElementGuid>28f83620-2e71-43fd-8c2f-522472530fc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://images.tokopedia.net/img/seller_no_logo_1.png' and @alt = 'Logo 4gungsh0p']</value>
      <webElementGuid>a4675a84-e2e3-4be7-bf05-23a18735891e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
