<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>buttonCloseShare</name>
   <tag></tag>
   <elementGuidId>f999703c-320d-4f14-9878-61fd8dee27b2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[contains(@src,'https://assets.tokopedia.net/asts/icons/nestIconClose2.svg')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Close&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>f116cf0a-e1f7-4e89-93db-bdef7ff64cbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>7c2343af-f545-469a-bdf4-bff2fd709533</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://assets.tokopedia.net/asts/icons/nestIconClose2.svg</value>
      <webElementGuid>72f861a7-eb45-4a63-93e2-eab5a68ac176</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>24</value>
      <webElementGuid>e35494fa-9a5b-4617-b559-759732b5ee65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>24</value>
      <webElementGuid>19fa909d-5802-4ddf-aa07-647a647e0c17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;pdp-container _1bjWexAK04P4u7su-8tlzQ==&quot;]/div[@class=&quot;rksrqdSSq0KxeLeSUKpgiQ== KHuWYbJKkK+T-MXGpMXx3A== gLoSVLlQHD4M8B8l2cb6lg==&quot;]/div[@class=&quot;SmN6QCP4AbBixrUfTJaxmw==&quot;]/button[@class=&quot;RB62KBoJWoqO7mBG8-IqLg==&quot;]/img[1]</value>
      <webElementGuid>c29c24b0-2588-4a0a-9d87-c99a0e5de724</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://assets.tokopedia.net/asts/icons/nestIconClose2.svg')]</value>
      <webElementGuid>816c3d2b-e831-4fb1-beb8-66f8a9598711</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/img</value>
      <webElementGuid>31801d7c-cf0a-47e8-84ee-ecae98de5091</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://assets.tokopedia.net/asts/icons/nestIconClose2.svg']</value>
      <webElementGuid>be923683-d39d-412d-94e7-2cb60b20722c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
