<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>buttonBeli</name>
   <tag></tag>
   <elementGuidId>813e9e94-3c1a-47b9-8a65-1268bc5f33d9</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'Beli' or . = 'Beli')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.css-16l1sjw-unf-btn.eg8apji0 > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='pdpFloatingActions']/div[4]/div/button[2]/span</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=&quot;pdpBtnNormalSecondary&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>b5a030b6-217d-40ca-bfdf-ac3720c06c6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Beli</value>
      <webElementGuid>8961ac72-1272-4d48-8e0b-546f47ba53d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pdpFloatingActions&quot;)/div[@class=&quot;css-qiunk2&quot;]/div[@class=&quot;css-c1hnei&quot;]/button[@class=&quot;css-16l1sjw-unf-btn eg8apji0&quot;]/span[1]</value>
      <webElementGuid>3732fd94-e51f-4d3f-96f0-e209b5096efe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pdpFloatingActions']/div[4]/div/button[2]/span</value>
      <webElementGuid>e45025c5-8ecc-4ba5-ab3f-ef47a3fd68e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='+ Keranjang'])[1]/following::span[1]</value>
      <webElementGuid>1f025111-7959-45af-a2b6-16eff0e8fa62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='jumlah'])[1]/following::span[2]</value>
      <webElementGuid>cc4a62b2-9bc9-44c0-8fcf-d03c6f9cf761</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Chat'])[1]/preceding::span[1]</value>
      <webElementGuid>f0b9f738-7eff-4d3d-be7d-6bc03a3fa4f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Wishlist'])[1]/preceding::span[1]</value>
      <webElementGuid>64512813-5777-4012-b93a-219726cdd9c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Beli']/parent::*</value>
      <webElementGuid>3afd32e0-ef79-4bf7-a4f4-0277bdeed6f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]/span</value>
      <webElementGuid>5ba8b489-a060-4c9c-b8ed-7f1b6e157f55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Beli' or . = 'Beli')]</value>
      <webElementGuid>feb67b84-390e-4e92-b9f5-504565a26fc6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
