<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>buttonSpesifikasi</name>
   <tag></tag>
   <elementGuidId>99c1c622-9e1b-40e4-b499-96e6e62bb310</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='pdp_comp-product_detail']/div[2]/div/div/button[2]/p</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.css-78ch3k-unf-tab-holder.ehv0kkf2 > button.tab-item.css-shh8ju.ehv0kkf3 > p.css-13xbs5z-unf-heading.e1qvo2ff8</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=tab[name=&quot;Spesifikasi&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>68921f31-17e0-4e38-8d96-78e10e64a0aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-unify</name>
      <type>Main</type>
      <value>Typography</value>
      <webElementGuid>cba6a591-dd9f-432d-981d-eb2b444b1d88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-13xbs5z-unf-heading e1qvo2ff8</value>
      <webElementGuid>dacecccd-8002-44c5-b97c-164a2a14b6b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Spesifikasi</value>
      <webElementGuid>5d584de7-2da3-4250-a67a-c1e747736f97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pdp_comp-product_detail&quot;)/div[2]/div[@class=&quot;css-1bl48du-unf-tab-wrapper ehv0kkf0&quot;]/div[@class=&quot;css-78ch3k-unf-tab-holder ehv0kkf2&quot;]/button[@class=&quot;tab-item css-shh8ju ehv0kkf3&quot;]/p[@class=&quot;css-13xbs5z-unf-heading e1qvo2ff8&quot;]</value>
      <webElementGuid>3410dc80-64c8-4ee6-8732-66830500dd7f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pdp_comp-product_detail']/div[2]/div/div/button[2]/p</value>
      <webElementGuid>ad17f922-f956-43b7-986a-4cd7cc63ffbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ungu'])[1]/following::p[2]</value>
      <webElementGuid>e125c14d-6b8c-49d2-b1ec-2efbe8f55448</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kondisi:'])[1]/preceding::p[1]</value>
      <webElementGuid>15188e22-9f1d-468b-b4d1-f325dc9168f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Baru'])[1]/preceding::p[1]</value>
      <webElementGuid>6805ba43-3933-4d6c-90ef-008a9e6669e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Spesifikasi']/parent::*</value>
      <webElementGuid>83650384-ca9f-4cec-a519-87bfdab2d1b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/button[2]/p</value>
      <webElementGuid>c624c406-71dc-4f4c-a405-a273044c6272</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Spesifikasi' or . = 'Spesifikasi')]</value>
      <webElementGuid>a86f6eb4-6de3-4383-80ec-dff071a117a6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
