<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iKondisi</name>
   <tag></tag>
   <elementGuidId>f921a951-5000-40e8-9614-b85334ed9e21</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='pdp_comp-product_detail']/div[2]/div[2]/ul/li/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.css-bwcbiv > span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Kondisi:&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c686e892-01a3-4fa9-afa4-850a1a215091</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Kondisi: </value>
      <webElementGuid>85e45725-43c0-4919-bf4a-c20a4765bf14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pdp_comp-product_detail&quot;)/div[2]/div[2]/ul[@class=&quot;css-1dqq1xv eytdjj02&quot;]/li[@class=&quot;css-bwcbiv&quot;]/span[1]</value>
      <webElementGuid>3624694a-7eeb-450b-b463-348e8ea6f5bf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pdp_comp-product_detail']/div[2]/div[2]/ul/li/span</value>
      <webElementGuid>ba4102a4-ef60-4967-8ed6-bc24b150840f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ungu'])[1]/following::span[1]</value>
      <webElementGuid>cc75ebeb-136d-43d1-ba10-9c92a87a3170</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Baru'])[1]/preceding::span[1]</value>
      <webElementGuid>45f21a0b-5d67-46c4-bd51-97d9ea54b74f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Min. Pemesanan:'])[1]/preceding::span[2]</value>
      <webElementGuid>f19d5138-4798-4965-82c5-765581b7f55b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Kondisi']/parent::*</value>
      <webElementGuid>86dd465b-996a-4b77-885a-f96d5134d059</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/span</value>
      <webElementGuid>57b88328-16c1-477e-8d3c-9fc51c84d826</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Kondisi: ' or . = 'Kondisi: ')]</value>
      <webElementGuid>5e868807-ff53-46bb-b308-ff3f1f65b0b1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
