<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iMinPemesanan</name>
   <tag></tag>
   <elementGuidId>9b317f8f-7b52-4d12-9b2e-fe281af17bbc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='pdp_comp-product_detail']/div[2]/div[2]/ul/li[2]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Min. Pemesanan:&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>9b2eee77-71f4-4591-896d-e5c377b83337</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Min. Pemesanan: </value>
      <webElementGuid>f4b35412-ffc0-4670-8dab-97315438a584</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pdp_comp-product_detail&quot;)/div[2]/div[2]/ul[@class=&quot;css-1dqq1xv eytdjj02&quot;]/li[@class=&quot;css-bwcbiv&quot;]/span[1]</value>
      <webElementGuid>0525c20a-306d-4464-932b-ab97a6b41e55</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pdp_comp-product_detail']/div[2]/div[2]/ul/li[2]/span</value>
      <webElementGuid>2270a25f-4155-44c9-b7be-6c8a1147a27b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Baru'])[1]/following::span[1]</value>
      <webElementGuid>26f90e1a-1cae-4557-91c2-64a08c690a46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kondisi:'])[1]/following::span[2]</value>
      <webElementGuid>c008647c-ab48-422c-9e7c-ff2e6d95a21b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Etalase:'])[1]/preceding::span[2]</value>
      <webElementGuid>a2301a13-1a41-4278-ad0d-2f2fa1621006</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Semua Etalase'])[1]/preceding::span[3]</value>
      <webElementGuid>3670584c-4a68-4bcb-9883-4cb6706e9106</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Min. Pemesanan']/parent::*</value>
      <webElementGuid>5b70521a-5198-4c08-8902-fda587103864</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/span</value>
      <webElementGuid>b62010eb-b1ff-411f-aca6-9415c9af1014</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Min. Pemesanan: ' or . = 'Min. Pemesanan: ')]</value>
      <webElementGuid>89fa58f6-f394-417a-abfe-6835fdacd45b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
