<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Terpilih Biru</name>
   <tag></tag>
   <elementGuidId>3390334c-ec28-4e26-bd03-be6e8c098df8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>p.css-18j10yz-unf-heading.e1qvo2ff8</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='pdpFloatingActions']/button/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Terpilih: Biru&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>a7048c36-525a-4178-b4d3-8d3b02161f33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-unify</name>
      <type>Main</type>
      <value>Typography</value>
      <webElementGuid>067f589e-a076-4859-aadb-feefd3491ee7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-18j10yz-unf-heading e1qvo2ff8</value>
      <webElementGuid>8270de51-29c0-4958-9342-c06d42db2d90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Terpilih: Biru</value>
      <webElementGuid>73e9b787-5320-4688-be7a-f559a25f7b32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pdpFloatingActions&quot;)/button[@class=&quot;css-i4q68g&quot;]/p[@class=&quot;css-18j10yz-unf-heading e1qvo2ff8&quot;]</value>
      <webElementGuid>526203e1-1c96-47e1-ac64-96fc4e71cb0b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pdpFloatingActions']/button/p</value>
      <webElementGuid>59c95f6e-079e-47ae-ad0b-94d53aae4d00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Atur jumlah dan catatan'])[1]/following::p[1]</value>
      <webElementGuid>a994c811-690c-4887-94f3-0328fd32e0af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Atasan wanita classic modern trendi - Biru'])[2]/following::p[2]</value>
      <webElementGuid>5a0dfed8-7786-4655-9cc6-c79bdadd087a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='jumlah'])[1]/preceding::p[1]</value>
      <webElementGuid>32a4ed88-a0ca-4100-926a-ecb66ba7c054</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/button/p</value>
      <webElementGuid>5f9e7698-9349-463d-9f94-828b4aaceb70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Terpilih: Biru' or . = 'Terpilih: Biru')]</value>
      <webElementGuid>228eeeb6-cabf-41b3-9ed2-1846737a9b6f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
