<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Terpilih Merah</name>
   <tag></tag>
   <elementGuidId>3e891ee8-cb34-4876-8ac7-e3ffe599dd74</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>p.css-18j10yz-unf-heading.e1qvo2ff8</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='pdpFloatingActions']/button/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Terpilih: Merah&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>480ec44e-1c12-4365-bf4a-0b78340c6e9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-unify</name>
      <type>Main</type>
      <value>Typography</value>
      <webElementGuid>7cc736c1-3136-47c7-89ef-8926a984583c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-18j10yz-unf-heading e1qvo2ff8</value>
      <webElementGuid>ee5811d6-714e-4323-867f-c45f73ae2082</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Terpilih: Merah</value>
      <webElementGuid>26367cad-5405-46bd-b3f5-4e0f045393ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pdpFloatingActions&quot;)/button[@class=&quot;css-i4q68g&quot;]/p[@class=&quot;css-18j10yz-unf-heading e1qvo2ff8&quot;]</value>
      <webElementGuid>e265db53-6d40-4473-9648-b11e71dfdc55</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pdpFloatingActions']/button/p</value>
      <webElementGuid>f3a184f6-9b96-4fb2-9b75-7649e00f26be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Atur jumlah dan catatan'])[1]/following::p[1]</value>
      <webElementGuid>f7538874-4dbc-49cb-b244-20557c00a957</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Atasan wanita classic modern trendi - Merah'])[2]/following::p[2]</value>
      <webElementGuid>2e8ba542-67d4-43e5-b61a-dd63b9259392</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='jumlah'])[1]/preceding::p[1]</value>
      <webElementGuid>edfa440f-3429-4876-ac5f-09a7de386e25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/button/p</value>
      <webElementGuid>1d848f66-12d0-4847-ba02-f0728dec1756</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Terpilih: Merah' or . = 'Terpilih: Merah')]</value>
      <webElementGuid>ddc2d2d2-924a-4331-84db-82f9a7a4a3c1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
