<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Terpilih Kuning</name>
   <tag></tag>
   <elementGuidId>198b5318-53f9-4404-8e51-5c5cd9ee7fc1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>p.css-18j10yz-unf-heading.e1qvo2ff8</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='pdpFloatingActions']/button/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Terpilih: Kuning&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>e2821dde-294c-40c5-88a7-606eb8f95859</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-unify</name>
      <type>Main</type>
      <value>Typography</value>
      <webElementGuid>13d3c117-3a04-44f9-8516-5b777dbf6007</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-18j10yz-unf-heading e1qvo2ff8</value>
      <webElementGuid>de4264d1-651e-405c-b6a5-64590cae6376</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Terpilih: Kuning</value>
      <webElementGuid>9611aa0b-1ee0-4935-8bc2-eca392864efa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pdpFloatingActions&quot;)/button[@class=&quot;css-i4q68g&quot;]/p[@class=&quot;css-18j10yz-unf-heading e1qvo2ff8&quot;]</value>
      <webElementGuid>e3e05ceb-e848-4c24-81ef-eef3d472f864</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pdpFloatingActions']/button/p</value>
      <webElementGuid>6233a490-92b6-4005-8f89-62d43e7eaa05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Atur jumlah dan catatan'])[1]/following::p[1]</value>
      <webElementGuid>614cb0da-610a-4dae-9ab2-4b64a6efb197</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Atasan wanita classic modern trendi - Kuning'])[2]/following::p[1]</value>
      <webElementGuid>d7b71cee-b77c-4d13-947a-bd4c055c814f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='jumlah'])[1]/preceding::p[1]</value>
      <webElementGuid>41b3836e-e324-4e0c-a4ad-2c0fb3f056c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Kuning']/parent::*</value>
      <webElementGuid>1130025d-41de-40ca-8357-2f374bfd1255</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/button/p</value>
      <webElementGuid>993acc3f-069e-4bc6-acee-b55e5d044966</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Terpilih: Kuning' or . = 'Terpilih: Kuning')]</value>
      <webElementGuid>42ba9bcf-ad86-469c-beb3-fc2aac0cd030</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
