<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>titleInfoProduct</name>
   <tag></tag>
   <elementGuidId>8043662d-52e7-48cb-89c4-430e8ed178ff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='pdp_comp-product_detail']/div[2]/div[2]/table/tr/th</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>th.level1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=cell[name=&quot;Info Produk&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>th</value>
      <webElementGuid>56319864-0788-4703-9d75-ae18af5bbd37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>level1</value>
      <webElementGuid>d5070088-da03-4e6f-82e0-a1c02cd4d291</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>colspan</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>0d600e20-b470-45f7-8b33-59bf1fed30de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Info Produk</value>
      <webElementGuid>7c8400de-b7b3-49b9-a3be-78eb6cf2ae4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pdp_comp-product_detail&quot;)/div[2]/div[@class=&quot;css-1i4r5m6&quot;]/table[1]/tr[1]/th[@class=&quot;level1&quot;]</value>
      <webElementGuid>2e810dac-3037-4b9c-8ffc-96ef451306dd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pdp_comp-product_detail']/div[2]/div[2]/table/tr/th</value>
      <webElementGuid>0c5b3383-a16e-45a6-8698-2a860f2de0d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ungu'])[1]/following::th[1]</value>
      <webElementGuid>6707dace-d3cc-4efd-8f8e-507b173398d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gaya Pakaian'])[1]/preceding::th[1]</value>
      <webElementGuid>f2d9eaae-b4e7-489c-9cb2-f82decc2f004</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=':'])[1]/preceding::th[2]</value>
      <webElementGuid>a879c168-4062-43c1-90bd-2e2d870c9e79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Info Produk']/parent::*</value>
      <webElementGuid>1ede36b1-1d5c-4a70-942b-2098ed797c7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th</value>
      <webElementGuid>63024e20-e06b-4f32-9d04-55be1d2832d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//th[(text() = 'Info Produk' or . = 'Info Produk')]</value>
      <webElementGuid>35dd10d5-6110-412e-a1f1-87400cfe8593</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
