<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>titleVariantChips3</name>
   <tag></tag>
   <elementGuidId>c5331b43-0c15-4dc6-b032-2832b83b9275</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='pdp_comp-product_content']/div/div/h1</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h1.css-1xfedof</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=&quot;lblPDPDetailProductName&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>f992cced-68f5-4ddd-b1f3-95a0c19aa3e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>5ccff333-20c0-487e-98a8-3f44715750fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-1xfedof</value>
      <webElementGuid>5e9a44ce-410f-47d4-bdb1-308741e1091c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>lblPDPDetailProductName</value>
      <webElementGuid>b784793f-c39f-4b89-b1ed-19c15a9f8b73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Atasan wanita classic modern trendi - Hitam</value>
      <webElementGuid>ea504b6d-582a-42da-9970-eadd76e7eb4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pdp_comp-product_content&quot;)/div[@class=&quot;css-jmbq56&quot;]/div[@class=&quot;css-1nylpq2&quot;]/h1[@class=&quot;css-1xfedof&quot;]</value>
      <webElementGuid>6aa2fc54-5596-4f63-af44-601cb0c66e89</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pdp_comp-product_content']/div/div/h1</value>
      <webElementGuid>a789ec8e-c6e7-4f48-9ff0-69590fbcd373</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Share'])[1]/following::h1[1]</value>
      <webElementGuid>ce0f7f46-222e-45c7-9d3f-fbf8ea040d0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Wishlist'])[1]/following::h1[1]</value>
      <webElementGuid>d511a9ff-bdf5-4a3a-b955-21b54b693d48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rp90.000'])[2]/preceding::h1[1]</value>
      <webElementGuid>c9ae5a4a-b39c-4a7b-adc9-2f37966f3d87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>cfc07f85-2ca7-4c53-b7d3-e3f88fd431e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = 'Atasan wanita classic modern trendi - Hitam' or . = 'Atasan wanita classic modern trendi - Hitam')]</value>
      <webElementGuid>8b503d11-7a5c-40e5-ab6d-1a9c574c4ce2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
