<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>titleVariantChips8</name>
   <tag></tag>
   <elementGuidId>0f52fec6-bf27-4d17-aed0-044b6430ea28</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='pdp_comp-product_content']/div/div/h1</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h1.css-1xfedof</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=&quot;lblPDPDetailProductName&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>2bd3b18e-af7e-41a9-bb9e-5236df366caf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>0ade780a-ed7d-4ccc-a449-085e74005492</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-1xfedof</value>
      <webElementGuid>85c55007-6724-4f0b-b8be-ddbfc863d96d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>lblPDPDetailProductName</value>
      <webElementGuid>6890d833-eb71-42f1-aabb-34482d52c904</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Atasan wanita classic modern trendi - Orange</value>
      <webElementGuid>b22620da-3a11-4798-a6b4-a38400e48f12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pdp_comp-product_content&quot;)/div[@class=&quot;css-jmbq56&quot;]/div[@class=&quot;css-1nylpq2&quot;]/h1[@class=&quot;css-1xfedof&quot;]</value>
      <webElementGuid>5bbcce54-9820-472f-8f7f-87c481723150</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pdp_comp-product_content']/div/div/h1</value>
      <webElementGuid>a29f55aa-2ac7-4efe-9ab6-ed8728489961</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Share'])[1]/following::h1[1]</value>
      <webElementGuid>0c736300-b6bd-4d41-a8eb-b0822f33bd39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Wishlist'])[1]/following::h1[1]</value>
      <webElementGuid>17e87f74-2ae2-450c-aeb7-76586282fd08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rp90.000'])[2]/preceding::h1[1]</value>
      <webElementGuid>37de8c5a-125b-41dc-bf9f-ab0fd3ad0a41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>139d9ce2-7fb6-4cd7-aaaa-55c1f0f68cd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = 'Atasan wanita classic modern trendi - Orange' or . = 'Atasan wanita classic modern trendi - Orange')]</value>
      <webElementGuid>d488bf99-096b-47d8-a80b-eda12b60b69a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
