<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>titleVariantChips4</name>
   <tag></tag>
   <elementGuidId>6ef926ab-b5ce-4853-9f7b-3b1e7538b2b0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='pdp_comp-product_content']/div/div/h1</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h1.css-1xfedof</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=&quot;lblPDPDetailProductName&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>de5d0c7e-505c-47a4-a7d1-ec30fa20ffc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>87945f8c-7a7f-4bbf-b962-66446ed6fb67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-1xfedof</value>
      <webElementGuid>388c8172-d519-4a4a-a227-dab556bd7026</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>lblPDPDetailProductName</value>
      <webElementGuid>5f2418db-6562-4c58-81b9-a6d7ba69ac65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Atasan wanita classic modern trendi - Kuning</value>
      <webElementGuid>6e0f8268-122e-4abc-9978-c0e887ce2d93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pdp_comp-product_content&quot;)/div[@class=&quot;css-jmbq56&quot;]/div[@class=&quot;css-1nylpq2&quot;]/h1[@class=&quot;css-1xfedof&quot;]</value>
      <webElementGuid>206e4130-bfeb-4508-9d2e-a1b634d1a7c4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pdp_comp-product_content']/div/div/h1</value>
      <webElementGuid>5d2b33df-ae76-4159-bdfc-982e8b0c257a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Share'])[1]/following::h1[1]</value>
      <webElementGuid>31387a86-cf93-4e3b-b10f-6381a4df8fcd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Wishlist'])[1]/following::h1[1]</value>
      <webElementGuid>432862ba-d801-4e25-9191-cfa5a0ee77be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rp90.000'])[2]/preceding::h1[1]</value>
      <webElementGuid>5beb1e0b-57aa-451e-b6be-9e07212ff12f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>b372bbfd-683e-45a4-90b3-b31f0de48adb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = 'Atasan wanita classic modern trendi - Kuning' or . = 'Atasan wanita classic modern trendi - Kuning')]</value>
      <webElementGuid>067bb813-21d5-484e-88bf-ca07f7f9fb20</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
