<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>titleVariantChips7</name>
   <tag></tag>
   <elementGuidId>aa0b44fe-2a45-4297-934d-29ead5b0ac1f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='pdp_comp-product_content']/div/div/h1</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h1.css-1xfedof</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=&quot;lblPDPDetailProductName&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>938f31d4-eae9-4a5b-9d01-476ffb2a4607</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>0b24ffd7-57eb-4ad4-8caf-5e04f5a28d2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-1xfedof</value>
      <webElementGuid>682b282b-c4f0-444e-a9b8-da7ff8b09511</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>lblPDPDetailProductName</value>
      <webElementGuid>73c49034-6a7c-4239-9f46-7e92d52155ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Atasan wanita classic modern trendi - Merah</value>
      <webElementGuid>a1777dc3-3eab-4e19-a8e7-ff177dc35220</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pdp_comp-product_content&quot;)/div[@class=&quot;css-jmbq56&quot;]/div[@class=&quot;css-1nylpq2&quot;]/h1[@class=&quot;css-1xfedof&quot;]</value>
      <webElementGuid>48054014-b07f-4157-8226-f214cd2b85b1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pdp_comp-product_content']/div/div/h1</value>
      <webElementGuid>e9fa1d65-b681-44f3-819d-cea79a810697</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Share'])[1]/following::h1[1]</value>
      <webElementGuid>7a01420d-2522-42f3-b0d2-233a3d3d70ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Wishlist'])[1]/following::h1[1]</value>
      <webElementGuid>c358fb65-81ce-4ee6-bfe3-7f8297a24e2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rp90.000'])[2]/preceding::h1[1]</value>
      <webElementGuid>d376970c-35f6-4902-b6f3-c6c277dbbf66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>fda5f0ff-55a3-4387-816e-2a1739b2a29b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = 'Atasan wanita classic modern trendi - Merah' or . = 'Atasan wanita classic modern trendi - Merah')]</value>
      <webElementGuid>ac1586e6-cfad-4ca3-b6b0-43f794497489</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
