<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>buttonAppStore</name>
   <tag></tag>
   <elementGuidId>cf39ce67-a962-486e-915a-71d63754a31c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;applestoreimage&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@alt='applestoreimage']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;applestoreimage&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>7deec3e5-4801-4335-a566-089b9984ca9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://assets.tokopedia.net/assets-tokopedia-lite/v2/zeus/kratos/4cc56a99.svg</value>
      <webElementGuid>bf39e4a3-5382-4bec-a976-6e10a09a54ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>112px</value>
      <webElementGuid>a4763e76-54d9-4140-93b5-e8e51534fb72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>33px</value>
      <webElementGuid>0589e3ef-d4cd-402b-9469-bd0e5477f8c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>applestoreimage</value>
      <webElementGuid>3cc68027-8b0c-4966-b1d5-a6fa96a86d96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;pdp-container css-1g5w2rw&quot;]/div[6]/div[@class=&quot;css-kl3gjj e1nc1fa20&quot;]/article[@class=&quot;G0cz1sg7XJmD3GZ6jLkBwQ== css-zagh8i-unf-modal e1nc1fa21&quot;]/div[@class=&quot;css-18qem4c e1nc1fa22&quot;]/div[@class=&quot;CZHM+-f4DSw016s2arLuMA==&quot;]/div[@class=&quot;EeFbzZgb+vo8aNlgxB6tYw==&quot;]/div[@class=&quot;_6CiGesQknRlundj5EKq7bg==&quot;]/div[2]/a[1]/img[1]</value>
      <webElementGuid>757a7574-afda-4a10-9db3-749cfccbba90</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='applestoreimage']</value>
      <webElementGuid>f6505dbc-1fb8-4cf4-abd1-e53f41c280aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/a/img</value>
      <webElementGuid>54ddb8c6-8dcf-4e89-9cb6-3aa59a6a3695</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://assets.tokopedia.net/assets-tokopedia-lite/v2/zeus/kratos/4cc56a99.svg' and @alt = 'applestoreimage']</value>
      <webElementGuid>b058a83c-091f-4b10-a263-5d49fa2eab51</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
