<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>buttonPlayStore</name>
   <tag></tag>
   <elementGuidId>4b4e1d41-d4ab-48a5-b802-b8a9e4be4b7a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;playstoreimage&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@alt='playstoreimage']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;playstoreimage&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>ed6f8504-64fa-48d6-9825-2a8ef7122933</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://assets.tokopedia.net/assets-tokopedia-lite/v2/zeus/kratos/e25ec508.svg</value>
      <webElementGuid>048ee78b-843a-4354-8546-dac45f388068</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>112px</value>
      <webElementGuid>5265527a-f193-4320-9161-2fdadb2b9226</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>33px</value>
      <webElementGuid>ec1453d2-b1b2-42a1-8242-31540c3ca49f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>playstoreimage</value>
      <webElementGuid>9c6d6bea-99a6-48a6-b51f-8addad43e2ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;pdp-container css-1g5w2rw&quot;]/div[6]/div[@class=&quot;css-kl3gjj e1nc1fa20&quot;]/article[@class=&quot;G0cz1sg7XJmD3GZ6jLkBwQ== css-zagh8i-unf-modal e1nc1fa21&quot;]/div[@class=&quot;css-18qem4c e1nc1fa22&quot;]/div[@class=&quot;CZHM+-f4DSw016s2arLuMA==&quot;]/div[@class=&quot;EeFbzZgb+vo8aNlgxB6tYw==&quot;]/div[@class=&quot;_6CiGesQknRlundj5EKq7bg==&quot;]/div[1]/a[1]/img[1]</value>
      <webElementGuid>5919bce5-5e40-4cb7-b6b2-e29840070890</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='playstoreimage']</value>
      <webElementGuid>9dd17843-cde3-41bf-9fe7-6b2eecd692af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/div/a/img</value>
      <webElementGuid>da979b0f-0f3c-4a53-a2e8-80b23c846183</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://assets.tokopedia.net/assets-tokopedia-lite/v2/zeus/kratos/e25ec508.svg' and @alt = 'playstoreimage']</value>
      <webElementGuid>9fec55a0-f2c2-4933-a617-6920f139f0d6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
