<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>titleOnPlayStore</name>
   <tag></tag>
   <elementGuidId>75eab8e5-ddbb-485d-953b-288c9d87dc61</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.AfwdI</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//body[@id='yDmH0d']/c-wiz[2]/div/div/div/div/div/div/div/c-wiz/div[2]/div/div/div/div/h1/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=heading[name=&quot;Tokopedia&quot;s] >> span</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>728172ef-fcd2-490e-9d36-656b640fe0a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>AfwdI</value>
      <webElementGuid>12b8cbb8-6d20-4dfb-b113-de8e7de92765</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>itemprop</name>
      <type>Main</type>
      <value>name</value>
      <webElementGuid>d2da3c2c-597b-4e24-8356-4e853880f6cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tokopedia</value>
      <webElementGuid>6c1c9e97-fddf-4f79-80d0-1eabb2600222</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;yDmH0d&quot;)/c-wiz[@class=&quot;SSPGKf Czez9d&quot;]/div[@class=&quot;T4LgNb&quot;]/div[@class=&quot;kFwPee&quot;]/div[1]/div[@class=&quot;tU8Y5c&quot;]/div[1]/div[@class=&quot;dzkqwc&quot;]/div[@class=&quot;wkMJlb YWi3ub&quot;]/c-wiz[1]/div[@class=&quot;hnnXjf&quot;]/div[@class=&quot;Il7kR&quot;]/div[@class=&quot;RhBWnf&quot;]/div[1]/div[@class=&quot;Fd93Bb ynrBgc xwcR9d&quot;]/h1[1]/span[@class=&quot;AfwdI&quot;]</value>
      <webElementGuid>58eb64fc-c80d-47e3-b257-5ebb4fcfa972</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='yDmH0d']/c-wiz[2]/div/div/div/div/div/div/div/c-wiz/div[2]/div/div/div/div/h1/span</value>
      <webElementGuid>ecd2d1c6-71a2-47c4-9992-c25abe80479b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kids'])[3]/following::span[1]</value>
      <webElementGuid>8aa242a5-95e3-41e5-93c2-72a35d725734</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Books'])[3]/following::span[1]</value>
      <webElementGuid>64f3dc8b-8601-44a5-98b9-7fb94b591446</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tokopedia'])[2]/preceding::span[1]</value>
      <webElementGuid>66499ead-5df6-4b70-bcb2-1617b0e99d0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Downloads'])[1]/preceding::span[2]</value>
      <webElementGuid>283b211a-68f9-49c9-b741-a029e4a73439</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Tokopedia']/parent::*</value>
      <webElementGuid>0cbb6b46-826b-4ad5-bc47-143e0210e5d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1/span</value>
      <webElementGuid>9b03e5eb-1e93-4c10-a48c-b20e776da61f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Tokopedia' or . = 'Tokopedia')]</value>
      <webElementGuid>6e706cf4-ba54-4b8c-aba8-eb506909c1d8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
