<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>buttonLaporkan</name>
   <tag></tag>
   <elementGuidId>2f49b3d8-ae24-450b-83a0-9f35639a2b98</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.css-l5hmv1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[37]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=&quot;btnReportProduct&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6e40b39c-57a1-4128-97e3-5d3579c9868b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>btnReportProduct</value>
      <webElementGuid>9322f183-c1ab-4b68-b6ec-d17d9f3a4f06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>bd812756-9b3d-44ce-a07d-f17591f38bc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-l5hmv1</value>
      <webElementGuid>324bbee8-bfe9-4d51-be97-9ba08532bf19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Laporkan</value>
      <webElementGuid>ed0644d6-58ed-4b97-a982-31d639602149</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pdp_comp-report&quot;)/div[@class=&quot;css-1p5njip&quot;]/button[@class=&quot;css-l5hmv1&quot;]</value>
      <webElementGuid>446a34b5-1cf9-4a75-bd1e-b2a2eb129c26</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[37]</value>
      <webElementGuid>95b1fae8-9ad3-4825-8a0a-b821173e73b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pdp_comp-report']/div[2]/button</value>
      <webElementGuid>3ea6a371-e674-430c-b4df-910346039af3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ada masalah dengan produk ini?'])[1]/following::button[1]</value>
      <webElementGuid>9c437506-c6cf-4ace-8c16-e67a35c41c90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Scan QR'])[1]/following::button[1]</value>
      <webElementGuid>e353aeae-513d-4d65-af40-40839f37c819</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ULASAN PEMBELI'])[1]/preceding::button[1]</value>
      <webElementGuid>31a33273-931b-4f13-877a-5295bdccc8bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Belum ada ulasan untuk produk ini'])[1]/preceding::button[1]</value>
      <webElementGuid>2b6e8ef8-e0c6-4b0f-acff-adfe1e78767e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Laporkan']/parent::*</value>
      <webElementGuid>cb9bd918-c176-427a-ad5e-220b100cfabd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/div[2]/button</value>
      <webElementGuid>cb5b16f5-5c1c-4a8d-ad0a-c2a5ea188043</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Laporkan' or . = 'Laporkan')]</value>
      <webElementGuid>c8c61d8e-9111-4f2b-920b-0ceb9abc3735</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
