<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>buttonLihatPilihanKurir</name>
   <tag></tag>
   <elementGuidId>3b8d4651-8214-46f7-b46e-b87f9a5229e0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[35]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.css-be8lbu</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=&quot;btnShowShipmentModal&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0db15c45-d928-4c85-85b2-26caa1f6e2b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9ae7aa53-c889-4fb6-9797-3d465d91737a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-be8lbu</value>
      <webElementGuid>0c13ca22-b3c6-4119-b5d9-f3c0565c863a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>btnShowShipmentModal</value>
      <webElementGuid>388d84ea-452f-474b-87d6-96660ea8e92a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Lihat Pilihan Kurir</value>
      <webElementGuid>f5e0b65a-603a-4a3f-af75-5478c45655f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pdp_comp-shipment&quot;)/div[@class=&quot;css-1yuhvjn&quot;]/div[1]/div[@class=&quot;css-1pv3cmv&quot;]/div[1]/div[@class=&quot;css-95g4uk&quot;]/div[@class=&quot;css-d0llh2&quot;]/button[@class=&quot;css-be8lbu&quot;]</value>
      <webElementGuid>0b3aba8b-df11-4787-91e2-39348f5c5a47</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[35]</value>
      <webElementGuid>37d7e0b2-f85e-4ce6-a8c2-58c6d79086fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pdp_comp-shipment']/div[2]/div/div[2]/div/div[2]/div[2]/button</value>
      <webElementGuid>75a87dc2-cf3f-4c6d-b0fc-bc8331427934</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Estimasi tiba besok - 25 Feb'])[1]/following::button[1]</value>
      <webElementGuid>092d090e-e5c8-479e-b86b-6e81180a7311</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ongkir Reguler 10 rb'])[1]/following::button[1]</value>
      <webElementGuid>20bbaae8-8089-408e-9ead-ed88dd158dc2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Beli di aplikasi, makin banyak promo!'])[1]/preceding::button[1]</value>
      <webElementGuid>4bce7850-463e-4606-8357-c7d7fe35c1b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Scan QR-nya untuk lihat barang ini di aplikasi Tokopedia. Bebas ongkir, lho~'])[1]/preceding::button[1]</value>
      <webElementGuid>bb8cfc55-184f-4038-adf2-d0ca290752ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Lihat Pilihan Kurir']/parent::*</value>
      <webElementGuid>0d394f41-8f41-44c5-b28e-21acbb8e4702</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/button</value>
      <webElementGuid>6929188e-15df-4732-9fa3-ad5a6ad264ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Lihat Pilihan Kurir' or . = 'Lihat Pilihan Kurir')]</value>
      <webElementGuid>bc651b16-95b6-46c3-b3fa-ce3307cefa86</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
