<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>buttonSemarang</name>
   <tag></tag>
   <elementGuidId>0c11bdad-8fa3-4734-bed7-91cef527c637</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[49]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Semarang&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>51c8f11b-2073-44ab-8227-99e6002b1f3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-unify</name>
      <type>Main</type>
      <value>Chip</value>
      <webElementGuid>c493252b-67c4-4707-b760-85f34ca462ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6bdc04e7-4219-4ef8-a7f4-29f8f5c9975a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-eylirg-unf-chip e6yxrl1</value>
      <webElementGuid>13779b44-8df1-4b05-af4f-c0c7de51418c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Semarang</value>
      <webElementGuid>32fc81be-233a-423c-b636-725cbbc2a7f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;pdp-container&quot;]/div[14]/div[@class=&quot;css-kl3gjj e1nc1fa20&quot;]/article[@class=&quot;css-z3221k-unf-modal e1nc1fa21&quot;]/div[@class=&quot;css-d6mneo e1nc1fa22&quot;]/div[1]/div[@class=&quot;_00-rei7R6H3SyhH6UV5V+A==&quot;]/div[@class=&quot;hBm3gluTQqs4Uc16UdxhcQ==&quot;]/div[@class=&quot;DljRmqt3mZdKNbhxHwaCpw==&quot;]/div[@class=&quot;dwpTnk6qWtcFd5zSdPWiwA==&quot;]/div[1]/div[@class=&quot;_7GeGMHv4+egKMeGfdi2pVA==&quot;]/button[@class=&quot;css-eylirg-unf-chip e6yxrl1&quot;]</value>
      <webElementGuid>9c40db23-e063-4b71-b0fd-228d11925f17</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[49]</value>
      <webElementGuid>1a7487e2-673c-4c33-8c6f-74f4a8b09617</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bogor'])[1]/following::button[1]</value>
      <webElementGuid>f0fd1961-890d-431b-9c64-86a76d00fabb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Depok'])[1]/following::button[2]</value>
      <webElementGuid>edf326be-5ef0-4f84-8c3f-c55dda472e85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Medan'])[1]/preceding::button[1]</value>
      <webElementGuid>4d0515da-f553-4946-8e67-04f724206fc2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Malang'])[1]/preceding::button[2]</value>
      <webElementGuid>1848fb9f-5fbe-41a2-9bfe-6f73c34db837</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Semarang']/parent::*</value>
      <webElementGuid>9acc2cb9-8072-43c7-a762-5b107edd3df7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button[8]</value>
      <webElementGuid>761bf391-b7ba-47ad-9ad7-979ff31e1a35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Semarang' or . = 'Semarang')]</value>
      <webElementGuid>8372ca61-e8c5-4186-9239-e610a0d3aea0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
