<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>fieldDestination</name>
   <tag></tag>
   <elementGuidId>13ad2781-8d33-4cca-8125-f47a5d6118bb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@value=''])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.css-1wtxb4b-input.euqom4f1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Pilih kota atau kecamatan&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>796b381c-f0bb-4cbd-b744-678bd4998136</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-unify</name>
      <type>Main</type>
      <value>TextField</value>
      <webElementGuid>7cbd3e04-8b18-4e16-af40-e5f629f1fca4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Pilih kota atau kecamatan</value>
      <webElementGuid>b50c32f2-5121-4b34-a42a-ad57bcc8d9a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6fc5356a-4714-4e84-b4aa-da97c54ba6c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-1wtxb4b-input euqom4f1</value>
      <webElementGuid>347bbfd5-f7e4-4c7a-99fc-584bb137c0b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;pdp-container&quot;]/div[14]/div[@class=&quot;css-kl3gjj e1nc1fa20&quot;]/article[@class=&quot;css-z3221k-unf-modal e1nc1fa21&quot;]/div[@class=&quot;css-d6mneo e1nc1fa22&quot;]/div[1]/div[@class=&quot;_00-rei7R6H3SyhH6UV5V+A==&quot;]/div[@class=&quot;hBm3gluTQqs4Uc16UdxhcQ==&quot;]/div[@class=&quot;DljRmqt3mZdKNbhxHwaCpw==&quot;]/div[1]/div[@class=&quot;css-cagx2s exxxdg60&quot;]/div[@class=&quot;css-wxqpmg-group exxxdg61&quot;]/div[@class=&quot;css-1gszrwr-container&quot;]/input[@class=&quot;css-1wtxb4b-input euqom4f1&quot;]</value>
      <webElementGuid>73f32c32-4f76-4570-b413-2d6193e0afd7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@value=''])[2]</value>
      <webElementGuid>21f6a124-be4f-426f-b311-5d8003301031</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>ac3afaaf-c3af-4d2b-aa46-ae24662972fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Pilih kota atau kecamatan' and @type = 'text']</value>
      <webElementGuid>9a048946-8c0e-42c7-bf34-404502d8a15d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
