<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>titleSimulasiPengiriman</name>
   <tag></tag>
   <elementGuidId>0626a2aa-de7d-4d8a-b5ad-21b257ff73f5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='unf-modal-title']/h5</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h5.css-fpj2nx-unf-heading.e1qvo2ff5</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=&quot;lblPDPInfoShipping&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h5</value>
      <webElementGuid>bd19bfc6-0e8e-47ac-8fd1-0b07ce3e8f97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-unify</name>
      <type>Main</type>
      <value>Typography</value>
      <webElementGuid>f9f42f81-e6ba-4c4b-a945-a22bb60f0254</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>lblPDPInfoShipping</value>
      <webElementGuid>eea8c3be-f10e-459f-94b4-3225d4bb726a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-fpj2nx-unf-heading e1qvo2ff5</value>
      <webElementGuid>fd647adc-518d-4d5d-a307-33ea76d6ebfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Simulasi Pengiriman</value>
      <webElementGuid>2b1c4bca-aaaf-4c5b-b086-aa4e249aaae5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;unf-modal-title&quot;)/h5[@class=&quot;css-fpj2nx-unf-heading e1qvo2ff5&quot;]</value>
      <webElementGuid>8214bb37-d229-4f72-a20a-e9c45e1624f7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='unf-modal-title']/h5</value>
      <webElementGuid>32cc2049-6c7f-4556-af69-cdc43b1ac4f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='English'])[1]/following::h5[1]</value>
      <webElementGuid>cac72736-67de-41cd-8bef-481c713faf77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Indonesia'])[1]/following::h5[1]</value>
      <webElementGuid>eff4361e-d8fa-4d77-8bdc-291110332a07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Berat barang'])[1]/preceding::h5[1]</value>
      <webElementGuid>2f67130c-5721-42ac-9edf-6a94f950f168</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dikirim dari'])[1]/preceding::h5[1]</value>
      <webElementGuid>40240166-9a32-4039-a140-fd54a10f0d5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Simulasi Pengiriman']/parent::*</value>
      <webElementGuid>c1e989e3-d802-4bf9-aa44-97259393efc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//header/div/h5</value>
      <webElementGuid>263b0bdb-4748-41ab-8d26-bf9e5dc21d48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h5[(text() = 'Simulasi Pengiriman' or . = 'Simulasi Pengiriman')]</value>
      <webElementGuid>b0bdb338-7cb7-406d-833e-d4316fd5e954</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
