<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Ulasan (1)</name>
   <tag></tag>
   <elementGuidId>20c58a6d-dd81-4526-ad86-ad4de266f0c9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>p.css-l5do8o-unf-heading.e1qvo2ff8 > a.css-q2y3yl</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='zeus-root']/div/div[2]/div[2]/div[2]/div/div/button[2]/p/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Ulasan&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f279980f-1963-4895-a251-bbaf3d8589e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-q2y3yl</value>
      <webElementGuid>dc756405-fb12-47f1-8c27-50f80c0124a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/4gungs/review</value>
      <webElementGuid>8d5e0d83-981c-42ac-9fc4-e5143920490d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ulasan</value>
      <webElementGuid>48b58f98-eae2-4e62-83f7-511e2c018308</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;zeus-root&quot;)/div[@class=&quot;css-8atqhb&quot;]/div[2]/div[@class=&quot;css-1s3ezns&quot;]/div[@class=&quot;css-79elbk&quot;]/div[@class=&quot;css-1bl48du-unf-tab-wrapper ehv0kkf0&quot;]/div[@class=&quot;css-twzod4-unf-tab-holder ehv0kkf2&quot;]/button[@class=&quot;css-3lvael ehv0kkf3&quot;]/p[@class=&quot;css-l5do8o-unf-heading e1qvo2ff8&quot;]/a[@class=&quot;css-q2y3yl&quot;]</value>
      <webElementGuid>5355095a-372c-4d46-bca5-98be51539891</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='zeus-root']/div/div[2]/div[2]/div[2]/div/div/button[2]/p/a</value>
      <webElementGuid>86b05698-3759-4e94-bcb6-af0e78274c49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Ulasan')]</value>
      <webElementGuid>fe87aae8-2ec4-4819-b499-2b9e21fd4342</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Produk'])[1]/following::a[1]</value>
      <webElementGuid>21962225-e16d-4ab1-968d-a1102d43c041</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bagikan'])[1]/following::a[2]</value>
      <webElementGuid>3ee36500-5ed5-4a63-af5b-deacb75b4041</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Belum ada rating dan ulasan produk di toko ini'])[1]/preceding::a[1]</value>
      <webElementGuid>cd2a5b39-3f29-4820-abac-8c64e1cadac2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Informasi Toko 4gungsh0p'])[1]/preceding::a[1]</value>
      <webElementGuid>cbe1253d-8042-40c5-980c-6687a0f0a9b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Ulasan']/parent::*</value>
      <webElementGuid>c560e709-a386-4a27-ab40-6d82dc2d8eef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/4gungs/review')]</value>
      <webElementGuid>44f39719-9d33-4eca-be1b-5cfa724c0aeb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]/p/a</value>
      <webElementGuid>7f907232-b31b-4f6b-8bba-c3a130652a1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/4gungs/review' and (text() = 'Ulasan' or . = 'Ulasan')]</value>
      <webElementGuid>4374493e-9f96-4fe7-8b2b-06987c10e466</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
