<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>buttonGoToShop</name>
   <tag></tag>
   <elementGuidId>208b4a02-640f-46cf-835c-919a486adb38</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h2.css-1wdzqxj-unf-heading.e1qvo2ff2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='pdp_comp-shop_credibility']/div[2]/div/div/div/a/h2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=&quot;llbPDPFooterShopName&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>59c04e86-fcd8-4c3a-a514-2dc2a0afd1c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-unify</name>
      <type>Main</type>
      <value>Typography</value>
      <webElementGuid>b67f691b-de0c-4964-a7ec-477960001eab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-1wdzqxj-unf-heading e1qvo2ff2</value>
      <webElementGuid>91a0bcf7-d670-45ad-8257-80731b9d30b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>4gungsh0p</value>
      <webElementGuid>b862321b-ffd3-4f33-b9fa-9a2bb5edf5ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pdp_comp-shop_credibility&quot;)/div[@class=&quot;css-1mxqisk&quot;]/div[@class=&quot;css-3v9jg2&quot;]/div[@class=&quot;css-i9gxme&quot;]/div[@class=&quot;css-k008qs&quot;]/a[@class=&quot;css-1sl4zpk&quot;]/h2[@class=&quot;css-1wdzqxj-unf-heading e1qvo2ff2&quot;]</value>
      <webElementGuid>35f8546e-8ede-4dac-9a8d-108fea46f405</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pdp_comp-shop_credibility']/div[2]/div/div/div/a/h2</value>
      <webElementGuid>e07c943b-5204-455d-87b3-ae7960201bf0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Baju atasan wanita classic dengan berbagai macam ukuran'])[1]/following::h2[1]</value>
      <webElementGuid>00945b02-8578-4e6e-99f6-f2b67ea95136</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Semua Etalase'])[1]/following::h2[1]</value>
      <webElementGuid>b9378b71-fe9f-4455-9e9a-14a28f3d892d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Follow'])[1]/preceding::h2[1]</value>
      <webElementGuid>ec5acaf8-89f2-431c-897b-1d475a4830cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='total barang'])[1]/preceding::h2[1]</value>
      <webElementGuid>032f0a2d-41ed-4d03-a0f2-76f529e2f060</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='4gungsh0p']/parent::*</value>
      <webElementGuid>eeed9560-1286-464e-926e-1f6be8207ae2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/h2</value>
      <webElementGuid>f3178b87-4780-48b4-8b1f-61eadf47b269</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[(text() = '4gungsh0p' or . = '4gungsh0p')]</value>
      <webElementGuid>8806bf9a-6a6f-45e4-89b6-94f307856011</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
