<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>buttonProdukTerjual</name>
   <tag></tag>
   <elementGuidId>588cf6a5-c9cf-43bd-9a9a-ca95acba92d2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.css-1239vz0 > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='zeus-root']/div/div[2]/div[2]/div[3]/aside/div/div/div/div/ul/li[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Produk Terjual&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>4f958159-ddbf-4e2a-acc7-3896154fc0a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/4gungs/etalase/sold?sort=7</value>
      <webElementGuid>1739f1f8-7d3f-455e-965e-7c96cb19de42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Produk Terjual</value>
      <webElementGuid>40ca367f-4ff5-446d-81d1-28f1e17316aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;zeus-root&quot;)/div[@class=&quot;css-8atqhb&quot;]/div[2]/div[@class=&quot;css-1s3ezns&quot;]/div[@class=&quot;css-1kn5b1o&quot;]/aside[@class=&quot;css-1u11ne2&quot;]/div[@class=&quot;css-1wyv5w4&quot;]/div[@class=&quot;css-7g2k08&quot;]/div[@class=&quot;header&quot;]/div[@class=&quot;css-148fuv6&quot;]/ul[@class=&quot;css-17mrx6g&quot;]/li[@class=&quot;css-1239vz0&quot;]/a[1]</value>
      <webElementGuid>2707a6e9-ba8a-45c4-8dbc-ac556df17815</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='zeus-root']/div/div[2]/div[2]/div[3]/aside/div/div/div/div/ul/li[2]/a</value>
      <webElementGuid>7e12d700-828f-466b-b794-227c0fdef5a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Produk Terjual')]</value>
      <webElementGuid>3c96d4fd-e7cc-47b6-b6b2-016127dc7edb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Semua Produk'])[1]/following::a[1]</value>
      <webElementGuid>fd4c5617-265e-4376-8d7d-efb720da36b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Etalase Toko (2)'])[1]/following::a[2]</value>
      <webElementGuid>e3ece838-2484-40ca-9d5f-03aedf39962c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Urutkan'])[1]/preceding::a[1]</value>
      <webElementGuid>d3ae4441-4cc7-4fcd-a286-d2beda41661e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Semua Produk'])[2]/preceding::a[1]</value>
      <webElementGuid>8a5c0de5-959c-4089-9e19-bdfb09ff2ae0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Produk Terjual']/parent::*</value>
      <webElementGuid>76e4e9be-d6d4-409d-8dd3-d3ce86b8fd3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/4gungs/etalase/sold?sort=7')]</value>
      <webElementGuid>47182fe3-be83-4a10-ba63-1af1c72a48fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a</value>
      <webElementGuid>0c847f8f-9842-4be6-a203-1ab2cc7068b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/4gungs/etalase/sold?sort=7' and (text() = 'Produk Terjual' or . = 'Produk Terjual')]</value>
      <webElementGuid>71f0b2db-93ba-41fc-8bb9-9ad8ba6902f8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
