<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>buttonUlasan</name>
   <tag></tag>
   <elementGuidId>c397f788-d119-4cf4-b368-af45c76494c4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>p.css-13xbs5z-unf-heading.e1qvo2ff8 > a.css-q2y3yl</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='zeus-root']/div/div[2]/div[2]/div[2]/div/div/button[2]/p/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Ulasan&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6eeaa4a6-c1d0-42f4-9236-0afc6ffab55b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-q2y3yl</value>
      <webElementGuid>22e652a8-755e-4f20-80cd-395153ad88e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/4gungs/review</value>
      <webElementGuid>31f0e09e-fd44-4418-8d1d-25c72b9dae47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ulasan</value>
      <webElementGuid>9dff1471-8391-4537-bbac-4138b23af945</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;zeus-root&quot;)/div[@class=&quot;css-8atqhb&quot;]/div[2]/div[@class=&quot;css-1s3ezns&quot;]/div[@class=&quot;css-79elbk&quot;]/div[@class=&quot;css-1bl48du-unf-tab-wrapper ehv0kkf0&quot;]/div[@class=&quot;css-twzod4-unf-tab-holder ehv0kkf2&quot;]/button[@class=&quot;css-shh8ju ehv0kkf3&quot;]/p[@class=&quot;css-13xbs5z-unf-heading e1qvo2ff8&quot;]/a[@class=&quot;css-q2y3yl&quot;]</value>
      <webElementGuid>b3a20b81-9df5-4970-86af-6e4f3cf5afe6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='zeus-root']/div/div[2]/div[2]/div[2]/div/div/button[2]/p/a</value>
      <webElementGuid>7644e0fc-805c-4f18-a2cf-f3f24e5c340e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Ulasan')]</value>
      <webElementGuid>5077cb52-810d-42b5-9cde-caa1146b6bd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Produk'])[1]/following::a[1]</value>
      <webElementGuid>592b44c9-3b51-44da-9583-68fc3c63c54c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bagikan'])[1]/following::a[2]</value>
      <webElementGuid>2b0e2419-c21e-4f79-81c1-d15711bfb76b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Etalase Toko (2)'])[1]/preceding::a[1]</value>
      <webElementGuid>382a991f-3b63-4ec5-8f63-4da4a9aca33c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Semua Produk'])[1]/preceding::a[1]</value>
      <webElementGuid>06678b33-09ed-4c35-8946-1801adc75007</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Ulasan']/parent::*</value>
      <webElementGuid>6ff233ed-40b1-4e52-956e-7650b0e9f70c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/4gungs/review')]</value>
      <webElementGuid>95c429b0-de20-4019-844d-291f1d5bbfc2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]/p/a</value>
      <webElementGuid>19816703-2ec7-4c5e-b21d-216e8195b540</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/4gungs/review' and (text() = 'Ulasan' or . = 'Ulasan')]</value>
      <webElementGuid>95e3bc46-1927-47f5-ab64-76e130a48dd2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
