<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>buttonShare</name>
   <tag></tag>
   <elementGuidId>0821b133-913a-4f2e-9376-e1f5ded5938c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[7]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=&quot;btnShareShop&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4a1f8f33-74af-4d59-9ad3-80364453a5a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-unify</name>
      <type>Main</type>
      <value>Button</value>
      <webElementGuid>a39ebf88-4456-4989-83cc-d65ab2b5549b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>404115b8-6c1e-49a9-a95e-6d1473be9a3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-edw0t8-unf-btn eg8apji0</value>
      <webElementGuid>a9ce91e5-fafa-4b5c-8652-d6140a45bc62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>btnShareShop</value>
      <webElementGuid>83bbab8d-c4b8-4a05-97e8-d84377d6912c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;zeus-root&quot;)/div[@class=&quot;css-8atqhb&quot;]/div[2]/div[@class=&quot;css-1s3ezns&quot;]/div[@class=&quot;css-11kmdxw&quot;]/div[@class=&quot;css-nqwx6t&quot;]/div[@class=&quot;css-5xpzqw e4r2vca0&quot;]/div[1]/div[@class=&quot;css-drikti e1ufc1ph1&quot;]/div[@class=&quot;css-1p0pkw3 e1ufc1ph0&quot;]/div[@class=&quot;css-43mjx7&quot;]/div[@class=&quot;css-1i27l4i&quot;]/div[@class=&quot;css-1xib5cx-unf-tooltip&quot;]/button[@class=&quot;css-edw0t8-unf-btn eg8apji0&quot;]</value>
      <webElementGuid>0f2a5257-05df-42e5-a83e-0650bf53f266</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[7]</value>
      <webElementGuid>f27e92f9-e651-47a7-9c3d-1001e32d7973</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='zeus-root']/div/div[2]/div[2]/div/div/div/div/div/div[2]/div/div[3]/div[2]/button</value>
      <webElementGuid>808fc0e6-9fb2-4310-93d1-72ec74c36578</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Info Toko'])[1]/following::button[1]</value>
      <webElementGuid>e7e1207e-73f1-45b1-93fc-a710bd53e078</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Chat Penjual'])[1]/following::button[2]</value>
      <webElementGuid>36907d4a-83c6-4fc2-b537-b140a19f20e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bagikan'])[1]/preceding::button[1]</value>
      <webElementGuid>31584e72-587a-495b-a412-49de99ba9545</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Produk'])[1]/preceding::button[1]</value>
      <webElementGuid>84dc9ddb-73dc-4e17-be01-19d3080dd58f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/button</value>
      <webElementGuid>2175e91e-42fe-4d0e-85f3-d0de17ff42d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button']</value>
      <webElementGuid>a4a43da9-b250-4cc9-abe5-f87caf4f69f7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
