<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>buttonProduk</name>
   <tag></tag>
   <elementGuidId>eb67e600-0b7d-4242-93e2-e3bc5cc66b9d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Ulasan'])[1]/preceding::a[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.css-q2y3yl</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=&quot;Produk&quot;] >> internal:role=link[name=&quot;Produk&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3e5e3638-c61d-4b57-854a-78c6ea571314</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-q2y3yl</value>
      <webElementGuid>097c7566-2942-491a-9a19-13f33bad1c53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/4gungs</value>
      <webElementGuid>6ba9060d-15de-4b33-8858-f7f205267e62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Produk</value>
      <webElementGuid>2bf4e16e-0fb2-4727-9fe3-8b0856635a70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;zeus-root&quot;)/div[@class=&quot;css-8atqhb&quot;]/div[2]/div[@class=&quot;css-1s3ezns&quot;]/div[@class=&quot;css-79elbk&quot;]/div[@class=&quot;css-1bl48du-unf-tab-wrapper ehv0kkf0&quot;]/div[@class=&quot;css-twzod4-unf-tab-holder ehv0kkf2&quot;]/button[@class=&quot;css-3lvael ehv0kkf3&quot;]/p[@class=&quot;css-l5do8o-unf-heading e1qvo2ff8&quot;]/a[@class=&quot;css-q2y3yl&quot;]</value>
      <webElementGuid>ccd733f4-1de7-4b89-ae68-110ab2f57265</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='zeus-root']/div/div[2]/div[2]/div[2]/div/div/button/p/a</value>
      <webElementGuid>37eaec82-c262-4c48-8ae4-ea2a4aafb56e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Produk')]</value>
      <webElementGuid>8e71dfc5-ab2a-4601-a93c-131d300a2a57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bagikan'])[1]/following::a[1]</value>
      <webElementGuid>db941d75-e5b3-4470-8fe4-d6b69b6182e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Info Toko'])[1]/following::a[1]</value>
      <webElementGuid>ec53ad27-c223-4765-a95b-c5a6daf69985</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ulasan'])[1]/preceding::a[1]</value>
      <webElementGuid>971c7b20-e550-43a8-8321-77680e6bdee8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Etalase Toko (2)'])[1]/preceding::a[2]</value>
      <webElementGuid>0fd53709-48c3-4ab2-8208-2952bfdf718a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Produk']/parent::*</value>
      <webElementGuid>2ff9b0f0-0509-446c-8cb3-a8580053acd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/4gungs')]</value>
      <webElementGuid>9c666614-caec-418f-a768-0ae4880cdf1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p/a</value>
      <webElementGuid>e631d711-6dc0-4c3c-87b4-650dee3e465b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/4gungs' and (text() = 'Produk' or . = 'Produk')]</value>
      <webElementGuid>01fab3fc-926c-42de-8521-31c4dfdb8411</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
