<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_4gungsh0p</name>
   <tag></tag>
   <elementGuidId>3a9c6e71-7840-43cb-a146-e1dc22bcb726</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h2.css-1wdzqxj-unf-heading.e1qvo2ff2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='pdp_comp-shop_credibility']/div[2]/div/div/div/a/h2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=&quot;llbPDPFooterShopName&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>77b4572f-9ab1-46f3-ae2f-8956d3c35c30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-unify</name>
      <type>Main</type>
      <value>Typography</value>
      <webElementGuid>23bb1f74-8165-4c73-b912-dadb1670045f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-1wdzqxj-unf-heading e1qvo2ff2</value>
      <webElementGuid>158fae02-c483-4d18-aa40-ed4ee3f9fd70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>4gungsh0p</value>
      <webElementGuid>62d5c1c5-1a34-4300-a9ca-79c66f98f081</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pdp_comp-shop_credibility&quot;)/div[@class=&quot;css-1mxqisk&quot;]/div[@class=&quot;css-3v9jg2&quot;]/div[@class=&quot;css-i9gxme&quot;]/div[@class=&quot;css-k008qs&quot;]/a[@class=&quot;css-1sl4zpk&quot;]/h2[@class=&quot;css-1wdzqxj-unf-heading e1qvo2ff2&quot;]</value>
      <webElementGuid>07752703-6fea-4583-93db-6a27ec31a04a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pdp_comp-shop_credibility']/div[2]/div/div/div/a/h2</value>
      <webElementGuid>82f92340-9862-4071-aa08-6ca796ed1605</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Baju atasan wanita classic dengan berbagai macam ukuran'])[1]/following::h2[1]</value>
      <webElementGuid>7e86f97d-9d1b-45b0-85f7-11cefdbb12bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Semua Etalase'])[1]/following::h2[1]</value>
      <webElementGuid>5c73173d-987e-41ec-8f72-eacaa9aa1306</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Follow'])[1]/preceding::h2[1]</value>
      <webElementGuid>d5499714-b4e8-427c-8840-03305dec665a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='total barang'])[1]/preceding::h2[1]</value>
      <webElementGuid>3da6db69-9aab-48b9-8a56-633df139b9e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='4gungsh0p']/parent::*</value>
      <webElementGuid>ab141b5f-f762-45e2-9900-428dc0c188d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/h2</value>
      <webElementGuid>de3bedba-a6a1-4dbd-a707-d0e366db6f8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[(text() = '4gungsh0p' or . = '4gungsh0p')]</value>
      <webElementGuid>87adb36a-55fe-48b3-a795-315ba4563cb1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
