<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>listProduct</name>
   <tag></tag>
   <elementGuidId>379f31bf-711d-45b3-9060-02db29f62835</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.css-1q90pod</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='zeus-root']/div/div[2]/div[2]/div[3]/div/div[2]/div/div/div/div/div/div/div/div/a/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Atasan wanita classic modern trendi&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>35502eab-bb48-42ea-b799-f2c7ef6f6bb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-1q90pod</value>
      <webElementGuid>2d8583bd-2048-4c41-8160-48a35504a4e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://images.tokopedia.net/img/cache/200-square/VqbcmM/2025/2/19/6068e1c8-525c-429e-a22d-c790380f9e92.jpg</value>
      <webElementGuid>e3206886-32cd-4f76-8760-5351aeb352f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Atasan wanita classic modern trendi</value>
      <webElementGuid>a9423745-139b-433a-936c-0fed8003171d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>imgProduct</value>
      <webElementGuid>d7d3284f-bfa4-4bd2-8c18-6db16ff3a8e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;zeus-root&quot;)/div[@class=&quot;css-8atqhb&quot;]/div[2]/div[@class=&quot;css-1s3ezns&quot;]/div[@class=&quot;css-1kn5b1o&quot;]/div[@class=&quot;css-1v9ovqz&quot;]/div[@class=&quot;css-8atqhb&quot;]/div[@class=&quot;css-tjjb18&quot;]/div[@class=&quot;css-1sn1xa2&quot;]/div[@class=&quot;css-54k5sq&quot;]/div[@class=&quot;css-uwyh54&quot;]/div[@class=&quot;css-qa82pd&quot;]/div[@class=&quot;prd_container-card css-126fhq2&quot;]/div[@class=&quot;pcv3__container css-1izdl9e&quot;]/div[@class=&quot;css-19oqosi&quot;]/a[1]/div[@class=&quot;pcv3_img_container css-1mygogd&quot;]/img[@class=&quot;css-1q90pod&quot;]</value>
      <webElementGuid>7d47077a-d246-483c-819b-0ac7a7d83710</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='zeus-root']/div/div[2]/div[2]/div[3]/div/div[2]/div/div/div/div/div/div/div/div/a/div/img</value>
      <webElementGuid>690bb3f1-24ab-4534-a09f-de0845b5c8c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Atasan wanita classic modern trendi']</value>
      <webElementGuid>b27714b7-7c8d-4629-ad12-c9a91176b892</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/img</value>
      <webElementGuid>f28813fa-2f31-44c5-9b25-0e433e312165</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://images.tokopedia.net/img/cache/200-square/VqbcmM/2025/2/19/6068e1c8-525c-429e-a22d-c790380f9e92.jpg' and @alt = 'Atasan wanita classic modern trendi']</value>
      <webElementGuid>99d23436-7f09-4aa3-927a-73e1be74a2d9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
