<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>titleBagikanKeTemanmu</name>
   <tag></tag>
   <elementGuidId>7cf858f2-d4cb-4096-bf41-a70fca741993</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h5.css-fpj2nx-unf-heading.e1qvo2ff5</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='unf-modal-title']/h5</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=heading[name=&quot;Bagikan ke Temanmu&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h5</value>
      <webElementGuid>58fa0ccc-d3e1-47f8-8093-f1abe8c6aa8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-unify</name>
      <type>Main</type>
      <value>Typography</value>
      <webElementGuid>20ecdddb-3a26-41d5-ada8-97308ce72b3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-fpj2nx-unf-heading e1qvo2ff5</value>
      <webElementGuid>42d9daa9-9fd7-42c1-85f7-bf38efb4512d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Bagikan ke Temanmu</value>
      <webElementGuid>06ecb12a-6731-4639-8fce-8f85d00ea6d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;unf-modal-title&quot;)/h5[@class=&quot;css-fpj2nx-unf-heading e1qvo2ff5&quot;]</value>
      <webElementGuid>765f1f79-15ba-4a89-aa0e-e5aabaf6111f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='unf-modal-title']/h5</value>
      <webElementGuid>4ef298db-6a75-4886-84fc-3b5624bbab3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='English'])[1]/following::h5[1]</value>
      <webElementGuid>4b93ce0e-0a66-4db7-8915-c0e091893242</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Indonesia'])[1]/following::h5[1]</value>
      <webElementGuid>3eb2503b-ea34-43ab-83fc-6a93a9bc32de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Bagikan ke Temanmu']/parent::*</value>
      <webElementGuid>47ae289f-2807-4302-b1cf-0644aca5984e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//header/div/h5</value>
      <webElementGuid>22d3d48f-c9f9-4df2-a04e-6452c09d116f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h5[(text() = 'Bagikan ke Temanmu' or . = 'Bagikan ke Temanmu')]</value>
      <webElementGuid>f11dfcd2-5027-4b41-bc95-8e2393c1645a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
