<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>titleShopName</name>
   <tag></tag>
   <elementGuidId>15ef6dcb-f968-4492-b497-ce0697f78369</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h2.css-1wdzqxj-unf-heading.e1qvo2ff2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*/text()[normalize-space(.)='4gungsh0p']/parent::*</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=&quot;llbPDPFooterShopName&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>2cbe3cb1-1158-495a-adfd-57c131b41c13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-unify</name>
      <type>Main</type>
      <value>Typography</value>
      <webElementGuid>20768bb2-3396-4685-9c5c-5942d5713502</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-1wdzqxj-unf-heading e1qvo2ff2</value>
      <webElementGuid>bff44da7-dfee-40d5-a9f8-67904413e55f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>4gungsh0p</value>
      <webElementGuid>836b7df9-9247-4f3d-85ac-3be75e97d6e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pdp_comp-shop_credibility&quot;)/div[@class=&quot;css-1mxqisk&quot;]/div[@class=&quot;css-3v9jg2&quot;]/div[@class=&quot;css-i9gxme&quot;]/div[@class=&quot;css-k008qs&quot;]/a[@class=&quot;css-1sl4zpk&quot;]/h2[@class=&quot;css-1wdzqxj-unf-heading e1qvo2ff2&quot;]</value>
      <webElementGuid>bbd4225c-040f-48c7-8b60-8048a28c820e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pdp_comp-shop_credibility']/div[2]/div/div/div/a/h2</value>
      <webElementGuid>2e974827-0b3d-443a-8db1-4f8a00b2eb54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Baju atasan wanita classic dengan berbagai macam ukuran'])[1]/following::h2[1]</value>
      <webElementGuid>caa2b6d1-25db-45b3-b67c-63148ce496ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Semua Etalase'])[1]/following::h2[1]</value>
      <webElementGuid>fb2ad989-1ab3-4af3-a6d8-68c2b93cd939</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Follow'])[1]/preceding::h2[1]</value>
      <webElementGuid>1eb4e674-8b5a-4385-a3d6-c8747f025ddb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='total barang'])[1]/preceding::h2[1]</value>
      <webElementGuid>251a09de-0379-4b3d-b175-1133e72ca016</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='4gungsh0p']/parent::*</value>
      <webElementGuid>de025aa7-cd85-4df0-8b0d-4e08dee3e550</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/h2</value>
      <webElementGuid>b67a2140-c733-4ca2-88f0-2e11b8faf6d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[(text() = '4gungsh0p' or . = '4gungsh0p')]</value>
      <webElementGuid>c7980411-c70a-48ff-99f9-0ddea5ed1cd1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
