<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnSwipe</name>
   <tag></tag>
   <elementGuidId>2b35a816-5a1a-42b7-a842-3f1ab1df6278</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[38]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.css-pwmkpk.css-1pmt71</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=&quot;btnPDPImageDetailNext&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a02417a4-15f4-4501-9d4d-e2588a67524a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e6185904-43b6-4261-b04d-5b77599a2614</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>btnPDPImageDetailNext</value>
      <webElementGuid>36ad79d5-dd2f-4db4-82d8-2598aca48172</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-pwmkpk css-1pmt71</value>
      <webElementGuid>8fe37c38-6a49-431b-813b-22f235a46a9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;pdp-container css-1g5w2rw&quot;]/div[6]/div[@class=&quot;css-846tch e1nc1fa20&quot;]/article[@class=&quot;css-1kkg083-unf-modal e1nc1fa21&quot;]/div[@class=&quot;css-eswunw e1nc1fa22&quot;]/div[@class=&quot;css-1qkj88q&quot;]/div[@class=&quot;css-1meeh3w&quot;]/button[@class=&quot;css-pwmkpk css-1pmt71&quot;]</value>
      <webElementGuid>501cf2d4-3a09-44d0-8711-a673bb6d2a8a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[38]</value>
      <webElementGuid>7efe085e-b73d-452b-8c08-f046c0324560</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//article/div/div/div/button</value>
      <webElementGuid>e7e9a1ac-be20-4f53-bbde-80d906791a39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button']</value>
      <webElementGuid>a390bfeb-53f9-46e5-9b50-746241741086</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
